---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/marcome2/public_html/preview/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R . $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/.git
    - /bin/rm -f $DEPLOYPATH/.cpanel.yml
    - /bin/rm -f $DEPLOYPATH/.gitignore
